/* tslint:disable */
/* eslint-disable */
/**
 * auth
 * Aicacia Auth API provides authentication services for applications.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * jsonwebtoken::Algorithm
 * @export
 */
export const Algorithm = {
    Hs256: 'HS256',
    Hs384: 'HS384',
    Hs512: 'HS512',
    Es256: 'ES256',
    Es384: 'ES384',
    Rs256: 'RS256',
    Rs384: 'RS384',
    Rs512: 'RS512',
    Ps256: 'PS256',
    Ps384: 'PS384',
    Ps512: 'PS512',
    EdDsa: 'EdDSA'
} as const;
export type Algorithm = typeof Algorithm[keyof typeof Algorithm];


export function instanceOfAlgorithm(value: any): boolean {
    for (const key in Algorithm) {
        if (Object.prototype.hasOwnProperty.call(Algorithm, key)) {
            if (Algorithm[key as keyof typeof Algorithm] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AlgorithmFromJSON(json: any): Algorithm {
    return AlgorithmFromJSONTyped(json, false);
}

export function AlgorithmFromJSONTyped(json: any, ignoreDiscriminator: boolean): Algorithm {
    return json as Algorithm;
}

export function AlgorithmToJSON(value?: Algorithm | null): any {
    return value as any;
}

export function AlgorithmToJSONTyped(value: any, ignoreDiscriminator: boolean): Algorithm {
    return value as Algorithm;
}

