/* tslint:disable */
/* eslint-disable */
/**
 * auth
 * Aicacia Auth
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApplicationPermission
 */
export interface ApplicationPermission {
    /**
     * 
     * @type {number}
     * @memberof ApplicationPermission
     */
    application_id: number;
    /**
     * 
     * @type {Date}
     * @memberof ApplicationPermission
     */
    created_at: Date;
    /**
     * 
     * @type {number}
     * @memberof ApplicationPermission
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof ApplicationPermission
     */
    name: string;
    /**
     * 
     * @type {Date}
     * @memberof ApplicationPermission
     */
    updated_at: Date;
    /**
     * 
     * @type {string}
     * @memberof ApplicationPermission
     */
    uri: string;
}

/**
 * Check if a given object implements the ApplicationPermission interface.
 */
export function instanceOfApplicationPermission(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "application_id" in value;
    isInstance = isInstance && "created_at" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "updated_at" in value;
    isInstance = isInstance && "uri" in value;

    return isInstance;
}

export function ApplicationPermissionFromJSON(json: any): ApplicationPermission {
    return ApplicationPermissionFromJSONTyped(json, false);
}

export function ApplicationPermissionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationPermission {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'application_id': json['application_id'],
        'created_at': (new Date(json['created_at'])),
        'id': json['id'],
        'name': json['name'],
        'updated_at': (new Date(json['updated_at'])),
        'uri': json['uri'],
    };
}

export function ApplicationPermissionToJSON(value?: ApplicationPermission | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'application_id': value.application_id,
        'created_at': (value.created_at.toISOString()),
        'id': value.id,
        'name': value.name,
        'updated_at': (value.updated_at.toISOString()),
        'uri': value.uri,
    };
}

