/* tslint:disable */
/* eslint-disable */
/**
 * auth
 * Aicacia Auth.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: nathanfaucett@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApplicationConfig
 */
export interface ApplicationConfig {
    /**
     * 
     * @type {Date}
     * @memberof ApplicationConfig
     */
    created_at: Date;
    /**
     * 
     * @type {string}
     * @memberof ApplicationConfig
     */
    key: string;
    /**
     * 
     * @type {Date}
     * @memberof ApplicationConfig
     */
    updated_at: Date;
    /**
     * 
     * @type {any}
     * @memberof ApplicationConfig
     */
    value: any | null;
}

/**
 * Check if a given object implements the ApplicationConfig interface.
 */
export function instanceOfApplicationConfig(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "created_at" in value;
    isInstance = isInstance && "key" in value;
    isInstance = isInstance && "updated_at" in value;
    isInstance = isInstance && "value" in value;

    return isInstance;
}

export function ApplicationConfigFromJSON(json: any): ApplicationConfig {
    return ApplicationConfigFromJSONTyped(json, false);
}

export function ApplicationConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationConfig {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'created_at': (new Date(json['created_at'])),
        'key': json['key'],
        'updated_at': (new Date(json['updated_at'])),
        'value': json['value'],
    };
}

export function ApplicationConfigToJSON(value?: ApplicationConfig | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'created_at': (value.created_at.toISOString()),
        'key': value.key,
        'updated_at': (value.updated_at.toISOString()),
        'value': value.value,
    };
}

