/* tslint:disable */
/* eslint-disable */
/**
 * auth
 * Aicacia Auth
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChangeUsernameRequest
 */
export interface ChangeUsernameRequest {
    /**
     * 
     * @type {string}
     * @memberof ChangeUsernameRequest
     */
    username: string;
}

/**
 * Check if a given object implements the ChangeUsernameRequest interface.
 */
export function instanceOfChangeUsernameRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "username" in value;

    return isInstance;
}

export function ChangeUsernameRequestFromJSON(json: any): ChangeUsernameRequest {
    return ChangeUsernameRequestFromJSONTyped(json, false);
}

export function ChangeUsernameRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangeUsernameRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'username': json['username'],
    };
}

export function ChangeUsernameRequestToJSON(value?: ChangeUsernameRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'username': value.username,
    };
}

