/* tslint:disable */
/* eslint-disable */
/**
 * auth
 * Aicacia Auth API provides authentication services for applications.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateUser
 */
export interface CreateUser {
    /**
     * 
     * @type {boolean}
     * @memberof CreateUser
     */
    active: boolean;
    /**
     * 
     * @type {string}
     * @memberof CreateUser
     */
    username: string;
}

/**
 * Check if a given object implements the CreateUser interface.
 */
export function instanceOfCreateUser(value: object): value is CreateUser {
    if (!('active' in value) || value['active'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    return true;
}

export function CreateUserFromJSON(json: any): CreateUser {
    return CreateUserFromJSONTyped(json, false);
}

export function CreateUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUser {
    if (json == null) {
        return json;
    }
    return {
        
        'active': json['active'],
        'username': json['username'],
    };
}

export function CreateUserToJSON(json: any): CreateUser {
    return CreateUserToJSONTyped(json, false);
}

export function CreateUserToJSONTyped(value?: CreateUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'active': value['active'],
        'username': value['username'],
    };
}

