/* tslint:disable */
/* eslint-disable */
/**
 * auth
 * Aicacia Auth API provides authentication services for applications.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Algorithm } from './Algorithm';
import {
    AlgorithmFromJSON,
    AlgorithmFromJSONTyped,
    AlgorithmToJSON,
    AlgorithmToJSONTyped,
} from './Algorithm';

/**
 * 
 * @export
 * @interface CreateTenant
 */
export interface CreateTenant {
    /**
     * 
     * @type {Algorithm}
     * @memberof CreateTenant
     */
    algorithm?: Algorithm | null;
    /**
     * 
     * @type {string}
     * @memberof CreateTenant
     */
    audience: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTenant
     */
    clientId?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CreateTenant
     */
    expiresInSeconds?: number | null;
    /**
     * 
     * @type {string}
     * @memberof CreateTenant
     */
    issuer: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTenant
     */
    privateKey?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateTenant
     */
    publicKey?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CreateTenant
     */
    refreshExpiresInSeconds?: number | null;
}



/**
 * Check if a given object implements the CreateTenant interface.
 */
export function instanceOfCreateTenant(value: object): value is CreateTenant {
    if (!('audience' in value) || value['audience'] === undefined) return false;
    if (!('issuer' in value) || value['issuer'] === undefined) return false;
    return true;
}

export function CreateTenantFromJSON(json: any): CreateTenant {
    return CreateTenantFromJSONTyped(json, false);
}

export function CreateTenantFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTenant {
    if (json == null) {
        return json;
    }
    return {
        
        'algorithm': json['algorithm'] == null ? undefined : AlgorithmFromJSON(json['algorithm']),
        'audience': json['audience'],
        'clientId': json['client_id'] == null ? undefined : json['client_id'],
        'expiresInSeconds': json['expires_in_seconds'] == null ? undefined : json['expires_in_seconds'],
        'issuer': json['issuer'],
        'privateKey': json['private_key'] == null ? undefined : json['private_key'],
        'publicKey': json['public_key'] == null ? undefined : json['public_key'],
        'refreshExpiresInSeconds': json['refresh_expires_in_seconds'] == null ? undefined : json['refresh_expires_in_seconds'],
    };
}

export function CreateTenantToJSON(json: any): CreateTenant {
    return CreateTenantToJSONTyped(json, false);
}

export function CreateTenantToJSONTyped(value?: CreateTenant | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'algorithm': AlgorithmToJSON(value['algorithm']),
        'audience': value['audience'],
        'client_id': value['clientId'],
        'expires_in_seconds': value['expiresInSeconds'],
        'issuer': value['issuer'],
        'private_key': value['privateKey'],
        'public_key': value['publicKey'],
        'refresh_expires_in_seconds': value['refreshExpiresInSeconds'],
    };
}

