/* tslint:disable */
/* eslint-disable */
/**
 * auth
 * Aicacia Auth API provides authentication services for applications.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateApplication
 */
export interface CreateApplication {
    /**
     * 
     * @type {string}
     * @memberof CreateApplication
     */
    name: string;
}

/**
 * Check if a given object implements the CreateApplication interface.
 */
export function instanceOfCreateApplication(value: object): value is CreateApplication {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateApplicationFromJSON(json: any): CreateApplication {
    return CreateApplicationFromJSONTyped(json, false);
}

export function CreateApplicationFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateApplication {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function CreateApplicationToJSON(json: any): CreateApplication {
    return CreateApplicationToJSONTyped(json, false);
}

export function CreateApplicationToJSONTyped(value?: CreateApplication | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

