/* tslint:disable */
/* eslint-disable */
/**
 * auth
 * Aicacia Auth.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: nathanfaucett@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateUserEmailRequest
 */
export interface CreateUserEmailRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateUserEmailRequest
     */
    email: string;
}

/**
 * Check if a given object implements the CreateUserEmailRequest interface.
 */
export function instanceOfCreateUserEmailRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "email" in value;

    return isInstance;
}

export function CreateUserEmailRequestFromJSON(json: any): CreateUserEmailRequest {
    return CreateUserEmailRequestFromJSONTyped(json, false);
}

export function CreateUserEmailRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUserEmailRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function CreateUserEmailRequestToJSON(value?: CreateUserEmailRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
    };
}

