/* tslint:disable */
/* eslint-disable */
/**
 * auth
 * Aicacia Auth API provides authentication services for applications.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateUserPhoneNumber
 */
export interface CreateUserPhoneNumber {
    /**
     * 
     * @type {string}
     * @memberof CreateUserPhoneNumber
     */
    phoneNumber: string;
}

/**
 * Check if a given object implements the CreateUserPhoneNumber interface.
 */
export function instanceOfCreateUserPhoneNumber(value: object): value is CreateUserPhoneNumber {
    if (!('phoneNumber' in value) || value['phoneNumber'] === undefined) return false;
    return true;
}

export function CreateUserPhoneNumberFromJSON(json: any): CreateUserPhoneNumber {
    return CreateUserPhoneNumberFromJSONTyped(json, false);
}

export function CreateUserPhoneNumberFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUserPhoneNumber {
    if (json == null) {
        return json;
    }
    return {
        
        'phoneNumber': json['phone_number'],
    };
}

export function CreateUserPhoneNumberToJSON(json: any): CreateUserPhoneNumber {
    return CreateUserPhoneNumberToJSONTyped(json, false);
}

export function CreateUserPhoneNumberToJSONTyped(value?: CreateUserPhoneNumber | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'phone_number': value['phoneNumber'],
    };
}

