/* tslint:disable */
/* eslint-disable */
/**
 * auth
 * Aicacia Auth API provides authentication services for applications.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { MFARequestServiceAccount } from './MFARequestServiceAccount';
import {
    instanceOfMFARequestServiceAccount,
    MFARequestServiceAccountFromJSON,
    MFARequestServiceAccountFromJSONTyped,
    MFARequestServiceAccountToJSON,
} from './MFARequestServiceAccount';
import type { MFARequestTOTP } from './MFARequestTOTP';
import {
    instanceOfMFARequestTOTP,
    MFARequestTOTPFromJSON,
    MFARequestTOTPFromJSONTyped,
    MFARequestTOTPToJSON,
} from './MFARequestTOTP';

/**
 * @type MFARequest
 * 
 * @export
 */
export type MFARequest = MFARequestServiceAccount | MFARequestTOTP;

export function MFARequestFromJSON(json: any): MFARequest {
    return MFARequestFromJSONTyped(json, false);
}

export function MFARequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MFARequest {
    if (json == null) {
        return json;
    }
    if (instanceOfMFARequestServiceAccount(json)) {
        return MFARequestServiceAccountFromJSONTyped(json, true);
    }
    if (instanceOfMFARequestTOTP(json)) {
        return MFARequestTOTPFromJSONTyped(json, true);
    }

    return {} as any;
}

export function MFARequestToJSON(json: any): any {
    return MFARequestToJSONTyped(json, false);
}

export function MFARequestToJSONTyped(value?: MFARequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    if (instanceOfMFARequestServiceAccount(value)) {
        return MFARequestServiceAccountToJSON(value as MFARequestServiceAccount);
    }
    if (instanceOfMFARequestTOTP(value)) {
        return MFARequestTOTPToJSON(value as MFARequestTOTP);
    }

    return {};
}

