/* tslint:disable */
/* eslint-disable */
/**
 * auth
 * Aicacia Auth API provides authentication services for applications.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisterUser
 */
export interface RegisterUser {
    /**
     * 
     * @type {string}
     * @memberof RegisterUser
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterUser
     */
    passwordConfirmation: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterUser
     */
    username: string;
}

/**
 * Check if a given object implements the RegisterUser interface.
 */
export function instanceOfRegisterUser(value: object): value is RegisterUser {
    if (!('password' in value) || value['password'] === undefined) return false;
    if (!('passwordConfirmation' in value) || value['passwordConfirmation'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    return true;
}

export function RegisterUserFromJSON(json: any): RegisterUser {
    return RegisterUserFromJSONTyped(json, false);
}

export function RegisterUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterUser {
    if (json == null) {
        return json;
    }
    return {
        
        'password': json['password'],
        'passwordConfirmation': json['password_confirmation'],
        'username': json['username'],
    };
}

export function RegisterUserToJSON(json: any): RegisterUser {
    return RegisterUserToJSONTyped(json, false);
}

export function RegisterUserToJSONTyped(value?: RegisterUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'password': value['password'],
        'password_confirmation': value['passwordConfirmation'],
        'username': value['username'],
    };
}

