/* tslint:disable */
/* eslint-disable */
/**
 * auth
 * Aicacia Auth
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResetPasswordRequest
 */
export interface ResetPasswordRequest {
    /**
     * 
     * @type {number}
     * @memberof ResetPasswordRequest
     */
    application_id: number;
    /**
     * 
     * @type {string}
     * @memberof ResetPasswordRequest
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof ResetPasswordRequest
     */
    password_confirmation: string;
    /**
     * 
     * @type {string}
     * @memberof ResetPasswordRequest
     */
    reset_password_token: string;
}

/**
 * Check if a given object implements the ResetPasswordRequest interface.
 */
export function instanceOfResetPasswordRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "application_id" in value;
    isInstance = isInstance && "password" in value;
    isInstance = isInstance && "password_confirmation" in value;
    isInstance = isInstance && "reset_password_token" in value;

    return isInstance;
}

export function ResetPasswordRequestFromJSON(json: any): ResetPasswordRequest {
    return ResetPasswordRequestFromJSONTyped(json, false);
}

export function ResetPasswordRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResetPasswordRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'application_id': json['application_id'],
        'password': json['password'],
        'password_confirmation': json['password_confirmation'],
        'reset_password_token': json['reset_password_token'],
    };
}

export function ResetPasswordRequestToJSON(value?: ResetPasswordRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'application_id': value.application_id,
        'password': value.password,
        'password_confirmation': value.password_confirmation,
        'reset_password_token': value.reset_password_token,
    };
}

