/* tslint:disable */
/* eslint-disable */
/**
 * auth
 * Aicacia Auth
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResetUserPasswordRequest
 */
export interface ResetUserPasswordRequest {
    /**
     * 
     * @type {string}
     * @memberof ResetUserPasswordRequest
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof ResetUserPasswordRequest
     */
    password_confirmation: string;
}

/**
 * Check if a given object implements the ResetUserPasswordRequest interface.
 */
export function instanceOfResetUserPasswordRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "password" in value;
    isInstance = isInstance && "password_confirmation" in value;

    return isInstance;
}

export function ResetUserPasswordRequestFromJSON(json: any): ResetUserPasswordRequest {
    return ResetUserPasswordRequestFromJSONTyped(json, false);
}

export function ResetUserPasswordRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResetUserPasswordRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'password': json['password'],
        'password_confirmation': json['password_confirmation'],
    };
}

export function ResetUserPasswordRequestToJSON(value?: ResetUserPasswordRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'password': value.password,
        'password_confirmation': value.password_confirmation,
    };
}

