/* tslint:disable */
/* eslint-disable */
/**
 * auth
 * Aicacia Auth API provides authentication services for applications.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ServiceAccount } from './ServiceAccount';
import {
    ServiceAccountFromJSON,
    ServiceAccountFromJSONTyped,
    ServiceAccountToJSON,
    ServiceAccountToJSONTyped,
} from './ServiceAccount';

/**
 * 
 * @export
 * @interface ServiceAccountPagination
 */
export interface ServiceAccountPagination {
    /**
     * 
     * @type {boolean}
     * @memberof ServiceAccountPagination
     */
    hasMore: boolean;
    /**
     * 
     * @type {Array<ServiceAccount>}
     * @memberof ServiceAccountPagination
     */
    items: Array<ServiceAccount>;
}

/**
 * Check if a given object implements the ServiceAccountPagination interface.
 */
export function instanceOfServiceAccountPagination(value: object): value is ServiceAccountPagination {
    if (!('hasMore' in value) || value['hasMore'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function ServiceAccountPaginationFromJSON(json: any): ServiceAccountPagination {
    return ServiceAccountPaginationFromJSONTyped(json, false);
}

export function ServiceAccountPaginationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceAccountPagination {
    if (json == null) {
        return json;
    }
    return {
        
        'hasMore': json['has_more'],
        'items': ((json['items'] as Array<any>).map(ServiceAccountFromJSON)),
    };
}

export function ServiceAccountPaginationToJSON(json: any): ServiceAccountPagination {
    return ServiceAccountPaginationToJSONTyped(json, false);
}

export function ServiceAccountPaginationToJSONTyped(value?: ServiceAccountPagination | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'has_more': value['hasMore'],
        'items': ((value['items'] as Array<any>).map(ServiceAccountToJSON)),
    };
}

