/* tslint:disable */
/* eslint-disable */
/**
 * auth
 * Aicacia Auth API provides authentication services for applications.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServiceAccountCreateUserEmail
 */
export interface ServiceAccountCreateUserEmail {
    /**
     * 
     * @type {string}
     * @memberof ServiceAccountCreateUserEmail
     */
    email: string;
    /**
     * 
     * @type {boolean}
     * @memberof ServiceAccountCreateUserEmail
     */
    primary?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof ServiceAccountCreateUserEmail
     */
    verified?: boolean | null;
}

/**
 * Check if a given object implements the ServiceAccountCreateUserEmail interface.
 */
export function instanceOfServiceAccountCreateUserEmail(value: object): value is ServiceAccountCreateUserEmail {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function ServiceAccountCreateUserEmailFromJSON(json: any): ServiceAccountCreateUserEmail {
    return ServiceAccountCreateUserEmailFromJSONTyped(json, false);
}

export function ServiceAccountCreateUserEmailFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceAccountCreateUserEmail {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'primary': json['primary'] == null ? undefined : json['primary'],
        'verified': json['verified'] == null ? undefined : json['verified'],
    };
}

export function ServiceAccountCreateUserEmailToJSON(json: any): ServiceAccountCreateUserEmail {
    return ServiceAccountCreateUserEmailToJSONTyped(json, false);
}

export function ServiceAccountCreateUserEmailToJSONTyped(value?: ServiceAccountCreateUserEmail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'primary': value['primary'],
        'verified': value['verified'],
    };
}

