/* tslint:disable */
/* eslint-disable */
/**
 * auth
 * Aicacia Auth API provides authentication services for applications.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServiceAccountUpdateUserPhoneNumber
 */
export interface ServiceAccountUpdateUserPhoneNumber {
    /**
     * 
     * @type {boolean}
     * @memberof ServiceAccountUpdateUserPhoneNumber
     */
    primary?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof ServiceAccountUpdateUserPhoneNumber
     */
    verified?: boolean | null;
}

/**
 * Check if a given object implements the ServiceAccountUpdateUserPhoneNumber interface.
 */
export function instanceOfServiceAccountUpdateUserPhoneNumber(value: object): value is ServiceAccountUpdateUserPhoneNumber {
    return true;
}

export function ServiceAccountUpdateUserPhoneNumberFromJSON(json: any): ServiceAccountUpdateUserPhoneNumber {
    return ServiceAccountUpdateUserPhoneNumberFromJSONTyped(json, false);
}

export function ServiceAccountUpdateUserPhoneNumberFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceAccountUpdateUserPhoneNumber {
    if (json == null) {
        return json;
    }
    return {
        
        'primary': json['primary'] == null ? undefined : json['primary'],
        'verified': json['verified'] == null ? undefined : json['verified'],
    };
}

export function ServiceAccountUpdateUserPhoneNumberToJSON(json: any): ServiceAccountUpdateUserPhoneNumber {
    return ServiceAccountUpdateUserPhoneNumberToJSONTyped(json, false);
}

export function ServiceAccountUpdateUserPhoneNumberToJSONTyped(value?: ServiceAccountUpdateUserPhoneNumber | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'primary': value['primary'],
        'verified': value['verified'],
    };
}

