/* tslint:disable */
/* eslint-disable */
/**
 * auth
 * Aicacia Auth
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SignUpMethods
 */
export interface SignUpMethods {
    /**
     * 
     * @type {boolean}
     * @memberof SignUpMethods
     */
    enabled: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SignUpMethods
     */
    password: boolean;
}

/**
 * Check if a given object implements the SignUpMethods interface.
 */
export function instanceOfSignUpMethods(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "enabled" in value;
    isInstance = isInstance && "password" in value;

    return isInstance;
}

export function SignUpMethodsFromJSON(json: any): SignUpMethods {
    return SignUpMethodsFromJSONTyped(json, false);
}

export function SignUpMethodsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignUpMethods {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'enabled': json['enabled'],
        'password': json['password'],
    };
}

export function SignUpMethodsToJSON(value?: SignUpMethods | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'enabled': value.enabled,
        'password': value.password,
    };
}

