/* tslint:disable */
/* eslint-disable */
/**
 * auth
 * Aicacia Auth
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SignInWithPasswordRequest
 */
export interface SignInWithPasswordRequest {
    /**
     * 
     * @type {number}
     * @memberof SignInWithPasswordRequest
     */
    application_id: number;
    /**
     * 
     * @type {string}
     * @memberof SignInWithPasswordRequest
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof SignInWithPasswordRequest
     */
    username_or_email: string;
}

/**
 * Check if a given object implements the SignInWithPasswordRequest interface.
 */
export function instanceOfSignInWithPasswordRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "application_id" in value;
    isInstance = isInstance && "password" in value;
    isInstance = isInstance && "username_or_email" in value;

    return isInstance;
}

export function SignInWithPasswordRequestFromJSON(json: any): SignInWithPasswordRequest {
    return SignInWithPasswordRequestFromJSONTyped(json, false);
}

export function SignInWithPasswordRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignInWithPasswordRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'application_id': json['application_id'],
        'password': json['password'],
        'username_or_email': json['username_or_email'],
    };
}

export function SignInWithPasswordRequestToJSON(value?: SignInWithPasswordRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'application_id': value.application_id,
        'password': value.password,
        'username_or_email': value.username_or_email,
    };
}

