/* tslint:disable */
/* eslint-disable */
/**
 * auth
 * Aicacia Auth
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SignUpWithPasswordRequest
 */
export interface SignUpWithPasswordRequest {
    /**
     * 
     * @type {string}
     * @memberof SignUpWithPasswordRequest
     */
    application_id: string;
    /**
     * 
     * @type {string}
     * @memberof SignUpWithPasswordRequest
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SignUpWithPasswordRequest
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof SignUpWithPasswordRequest
     */
    password_confirmation: string;
    /**
     * 
     * @type {string}
     * @memberof SignUpWithPasswordRequest
     */
    username: string;
}

/**
 * Check if a given object implements the SignUpWithPasswordRequest interface.
 */
export function instanceOfSignUpWithPasswordRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "application_id" in value;
    isInstance = isInstance && "password" in value;
    isInstance = isInstance && "password_confirmation" in value;
    isInstance = isInstance && "username" in value;

    return isInstance;
}

export function SignUpWithPasswordRequestFromJSON(json: any): SignUpWithPasswordRequest {
    return SignUpWithPasswordRequestFromJSONTyped(json, false);
}

export function SignUpWithPasswordRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignUpWithPasswordRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'application_id': json['application_id'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'password': json['password'],
        'password_confirmation': json['password_confirmation'],
        'username': json['username'],
    };
}

export function SignUpWithPasswordRequestToJSON(value?: SignUpWithPasswordRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'application_id': value.application_id,
        'email': value.email,
        'password': value.password,
        'password_confirmation': value.password_confirmation,
        'username': value.username,
    };
}

