/* tslint:disable */
/* eslint-disable */
/**
 * auth
 * Aicacia Auth API provides authentication services for applications.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TokenRequestServiceAccount
 */
export interface TokenRequestServiceAccount {
    /**
     * 
     * @type {string}
     * @memberof TokenRequestServiceAccount
     */
    clientId: string;
    /**
     * 
     * @type {string}
     * @memberof TokenRequestServiceAccount
     */
    clientSecret: string;
    /**
     * 
     * @type {string}
     * @memberof TokenRequestServiceAccount
     */
    grantType: TokenRequestServiceAccountGrantTypeEnum;
}


/**
 * @export
 */
export const TokenRequestServiceAccountGrantTypeEnum = {
    ServiceAccount: 'service-account'
} as const;
export type TokenRequestServiceAccountGrantTypeEnum = typeof TokenRequestServiceAccountGrantTypeEnum[keyof typeof TokenRequestServiceAccountGrantTypeEnum];


/**
 * Check if a given object implements the TokenRequestServiceAccount interface.
 */
export function instanceOfTokenRequestServiceAccount(value: object): value is TokenRequestServiceAccount {
    if (!('clientId' in value) || value['clientId'] === undefined) return false;
    if (!('clientSecret' in value) || value['clientSecret'] === undefined) return false;
    if (!('grantType' in value) || value['grantType'] === undefined) return false;
    return true;
}

export function TokenRequestServiceAccountFromJSON(json: any): TokenRequestServiceAccount {
    return TokenRequestServiceAccountFromJSONTyped(json, false);
}

export function TokenRequestServiceAccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenRequestServiceAccount {
    if (json == null) {
        return json;
    }
    return {
        
        'clientId': json['client_id'],
        'clientSecret': json['client_secret'],
        'grantType': json['grant_type'],
    };
}

export function TokenRequestServiceAccountToJSON(json: any): TokenRequestServiceAccount {
    return TokenRequestServiceAccountToJSONTyped(json, false);
}

export function TokenRequestServiceAccountToJSONTyped(value?: TokenRequestServiceAccount | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'client_id': value['clientId'],
        'client_secret': value['clientSecret'],
        'grant_type': value['grantType'],
    };
}

