/* tslint:disable */
/* eslint-disable */
/**
 * auth
 * Aicacia Auth API provides authentication services for applications.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateServiceAccount
 */
export interface UpdateServiceAccount {
    /**
     * 
     * @type {boolean}
     * @memberof UpdateServiceAccount
     */
    active?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateServiceAccount
     */
    admin?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateServiceAccount
     */
    clientId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateServiceAccount
     */
    clientSecret?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateServiceAccount
     */
    name?: string | null;
}

/**
 * Check if a given object implements the UpdateServiceAccount interface.
 */
export function instanceOfUpdateServiceAccount(value: object): value is UpdateServiceAccount {
    return true;
}

export function UpdateServiceAccountFromJSON(json: any): UpdateServiceAccount {
    return UpdateServiceAccountFromJSONTyped(json, false);
}

export function UpdateServiceAccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateServiceAccount {
    if (json == null) {
        return json;
    }
    return {
        
        'active': json['active'] == null ? undefined : json['active'],
        'admin': json['admin'] == null ? undefined : json['admin'],
        'clientId': json['client_id'] == null ? undefined : json['client_id'],
        'clientSecret': json['client_secret'] == null ? undefined : json['client_secret'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function UpdateServiceAccountToJSON(json: any): UpdateServiceAccount {
    return UpdateServiceAccountToJSONTyped(json, false);
}

export function UpdateServiceAccountToJSONTyped(value?: UpdateServiceAccount | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'active': value['active'],
        'admin': value['admin'],
        'client_id': value['clientId'],
        'client_secret': value['clientSecret'],
        'name': value['name'],
    };
}

