/* tslint:disable */
/* eslint-disable */
/**
 * auth
 * Aicacia Auth API provides authentication services for applications.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Algorithm } from './Algorithm';
import {
    AlgorithmFromJSON,
    AlgorithmFromJSONTyped,
    AlgorithmToJSON,
    AlgorithmToJSONTyped,
} from './Algorithm';

/**
 * 
 * @export
 * @interface UpdateTenant
 */
export interface UpdateTenant {
    /**
     * 
     * @type {Algorithm}
     * @memberof UpdateTenant
     */
    algorithm?: Algorithm | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateTenant
     */
    audience?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateTenant
     */
    clientId?: string | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateTenant
     */
    expiresInSeconds?: number | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateTenant
     */
    issuer?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateTenant
     */
    privateKey?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateTenant
     */
    publicKey?: string | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateTenant
     */
    refreshExpiresInSeconds?: number | null;
}



/**
 * Check if a given object implements the UpdateTenant interface.
 */
export function instanceOfUpdateTenant(value: object): value is UpdateTenant {
    return true;
}

export function UpdateTenantFromJSON(json: any): UpdateTenant {
    return UpdateTenantFromJSONTyped(json, false);
}

export function UpdateTenantFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTenant {
    if (json == null) {
        return json;
    }
    return {
        
        'algorithm': json['algorithm'] == null ? undefined : AlgorithmFromJSON(json['algorithm']),
        'audience': json['audience'] == null ? undefined : json['audience'],
        'clientId': json['client_id'] == null ? undefined : json['client_id'],
        'expiresInSeconds': json['expires_in_seconds'] == null ? undefined : json['expires_in_seconds'],
        'issuer': json['issuer'] == null ? undefined : json['issuer'],
        'privateKey': json['private_key'] == null ? undefined : json['private_key'],
        'publicKey': json['public_key'] == null ? undefined : json['public_key'],
        'refreshExpiresInSeconds': json['refresh_expires_in_seconds'] == null ? undefined : json['refresh_expires_in_seconds'],
    };
}

export function UpdateTenantToJSON(json: any): UpdateTenant {
    return UpdateTenantToJSONTyped(json, false);
}

export function UpdateTenantToJSONTyped(value?: UpdateTenant | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'algorithm': AlgorithmToJSON(value['algorithm']),
        'audience': value['audience'],
        'client_id': value['clientId'],
        'expires_in_seconds': value['expiresInSeconds'],
        'issuer': value['issuer'],
        'private_key': value['privateKey'],
        'public_key': value['publicKey'],
        'refresh_expires_in_seconds': value['refreshExpiresInSeconds'],
    };
}

