/* tslint:disable */
/* eslint-disable */
/**
 * auth
 * Aicacia Auth API provides authentication services for applications.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateApplication
 */
export interface UpdateApplication {
    /**
     * 
     * @type {string}
     * @memberof UpdateApplication
     */
    name?: string | null;
}

/**
 * Check if a given object implements the UpdateApplication interface.
 */
export function instanceOfUpdateApplication(value: object): value is UpdateApplication {
    return true;
}

export function UpdateApplicationFromJSON(json: any): UpdateApplication {
    return UpdateApplicationFromJSONTyped(json, false);
}

export function UpdateApplicationFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateApplication {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function UpdateApplicationToJSON(json: any): UpdateApplication {
    return UpdateApplicationToJSONTyped(json, false);
}

export function UpdateApplicationToJSONTyped(value?: UpdateApplication | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

