/* tslint:disable */
/* eslint-disable */
/**
 * auth
 * Aicacia Auth API provides authentication services for applications.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserMFAType } from './UserMFAType';
import {
    UserMFATypeFromJSON,
    UserMFATypeFromJSONTyped,
    UserMFATypeToJSON,
    UserMFATypeToJSONTyped,
} from './UserMFAType';

/**
 * 
 * @export
 * @interface UpdateUserConfigRequest
 */
export interface UpdateUserConfigRequest {
    /**
     * 
     * @type {UserMFAType}
     * @memberof UpdateUserConfigRequest
     */
    mfaType?: UserMFAType | null;
}



/**
 * Check if a given object implements the UpdateUserConfigRequest interface.
 */
export function instanceOfUpdateUserConfigRequest(value: object): value is UpdateUserConfigRequest {
    return true;
}

export function UpdateUserConfigRequestFromJSON(json: any): UpdateUserConfigRequest {
    return UpdateUserConfigRequestFromJSONTyped(json, false);
}

export function UpdateUserConfigRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateUserConfigRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'mfaType': json['mfa_type'] == null ? undefined : UserMFATypeFromJSON(json['mfa_type']),
    };
}

export function UpdateUserConfigRequestToJSON(json: any): UpdateUserConfigRequest {
    return UpdateUserConfigRequestToJSONTyped(json, false);
}

export function UpdateUserConfigRequestToJSONTyped(value?: UpdateUserConfigRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mfa_type': UserMFATypeToJSON(value['mfaType']),
    };
}

