/* tslint:disable */
/* eslint-disable */
/**
 * auth
 * Aicacia Auth API provides authentication services for applications.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateUserInfoRequest
 */
export interface UpdateUserInfoRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateUserInfoRequest
     */
    address?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof UpdateUserInfoRequest
     */
    birthdate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserInfoRequest
     */
    familyName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserInfoRequest
     */
    gender?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserInfoRequest
     */
    givenName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserInfoRequest
     */
    locale?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserInfoRequest
     */
    middleName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserInfoRequest
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserInfoRequest
     */
    nickname?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserInfoRequest
     */
    profilePicture?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserInfoRequest
     */
    website?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserInfoRequest
     */
    zoneInfo?: string | null;
}

/**
 * Check if a given object implements the UpdateUserInfoRequest interface.
 */
export function instanceOfUpdateUserInfoRequest(value: object): value is UpdateUserInfoRequest {
    return true;
}

export function UpdateUserInfoRequestFromJSON(json: any): UpdateUserInfoRequest {
    return UpdateUserInfoRequestFromJSONTyped(json, false);
}

export function UpdateUserInfoRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateUserInfoRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'] == null ? undefined : json['address'],
        'birthdate': json['birthdate'] == null ? undefined : (new Date(json['birthdate'])),
        'familyName': json['family_name'] == null ? undefined : json['family_name'],
        'gender': json['gender'] == null ? undefined : json['gender'],
        'givenName': json['given_name'] == null ? undefined : json['given_name'],
        'locale': json['locale'] == null ? undefined : json['locale'],
        'middleName': json['middle_name'] == null ? undefined : json['middle_name'],
        'name': json['name'] == null ? undefined : json['name'],
        'nickname': json['nickname'] == null ? undefined : json['nickname'],
        'profilePicture': json['profile_picture'] == null ? undefined : json['profile_picture'],
        'website': json['website'] == null ? undefined : json['website'],
        'zoneInfo': json['zone_info'] == null ? undefined : json['zone_info'],
    };
}

export function UpdateUserInfoRequestToJSON(json: any): UpdateUserInfoRequest {
    return UpdateUserInfoRequestToJSONTyped(json, false);
}

export function UpdateUserInfoRequestToJSONTyped(value?: UpdateUserInfoRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address': value['address'],
        'birthdate': value['birthdate'] == null ? undefined : ((value['birthdate'] as any).toISOString()),
        'family_name': value['familyName'],
        'gender': value['gender'],
        'given_name': value['givenName'],
        'locale': value['locale'],
        'middle_name': value['middleName'],
        'name': value['name'],
        'nickname': value['nickname'],
        'profile_picture': value['profilePicture'],
        'website': value['website'],
        'zone_info': value['zoneInfo'],
    };
}

