/* tslint:disable */
/* eslint-disable */
/**
 * auth
 * Aicacia Auth API provides authentication services for applications.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateTenantOAuth2Provider
 */
export interface UpdateTenantOAuth2Provider {
    /**
     * 
     * @type {boolean}
     * @memberof UpdateTenantOAuth2Provider
     */
    active?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateTenantOAuth2Provider
     */
    authUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateTenantOAuth2Provider
     */
    callbackUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateTenantOAuth2Provider
     */
    clientId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateTenantOAuth2Provider
     */
    clientSecret?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateTenantOAuth2Provider
     */
    redirectUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateTenantOAuth2Provider
     */
    scope?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateTenantOAuth2Provider
     */
    tokenUrl?: string | null;
}

/**
 * Check if a given object implements the UpdateTenantOAuth2Provider interface.
 */
export function instanceOfUpdateTenantOAuth2Provider(value: object): value is UpdateTenantOAuth2Provider {
    return true;
}

export function UpdateTenantOAuth2ProviderFromJSON(json: any): UpdateTenantOAuth2Provider {
    return UpdateTenantOAuth2ProviderFromJSONTyped(json, false);
}

export function UpdateTenantOAuth2ProviderFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTenantOAuth2Provider {
    if (json == null) {
        return json;
    }
    return {
        
        'active': json['active'] == null ? undefined : json['active'],
        'authUrl': json['auth_url'] == null ? undefined : json['auth_url'],
        'callbackUrl': json['callback_url'] == null ? undefined : json['callback_url'],
        'clientId': json['client_id'] == null ? undefined : json['client_id'],
        'clientSecret': json['client_secret'] == null ? undefined : json['client_secret'],
        'redirectUrl': json['redirect_url'] == null ? undefined : json['redirect_url'],
        'scope': json['scope'] == null ? undefined : json['scope'],
        'tokenUrl': json['token_url'] == null ? undefined : json['token_url'],
    };
}

export function UpdateTenantOAuth2ProviderToJSON(json: any): UpdateTenantOAuth2Provider {
    return UpdateTenantOAuth2ProviderToJSONTyped(json, false);
}

export function UpdateTenantOAuth2ProviderToJSONTyped(value?: UpdateTenantOAuth2Provider | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'active': value['active'],
        'auth_url': value['authUrl'],
        'callback_url': value['callbackUrl'],
        'client_id': value['clientId'],
        'client_secret': value['clientSecret'],
        'redirect_url': value['redirectUrl'],
        'scope': value['scope'],
        'token_url': value['tokenUrl'],
    };
}

