/* tslint:disable */
/* eslint-disable */
/**
 * auth
 * Aicacia Auth.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: nathanfaucett@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateApplicationConfigRequest
 */
export interface UpdateApplicationConfigRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateApplicationConfigRequest
     */
    key: string;
    /**
     * 
     * @type {any}
     * @memberof UpdateApplicationConfigRequest
     */
    value: any | null;
}

/**
 * Check if a given object implements the UpdateApplicationConfigRequest interface.
 */
export function instanceOfUpdateApplicationConfigRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "key" in value;
    isInstance = isInstance && "value" in value;

    return isInstance;
}

export function UpdateApplicationConfigRequestFromJSON(json: any): UpdateApplicationConfigRequest {
    return UpdateApplicationConfigRequestFromJSONTyped(json, false);
}

export function UpdateApplicationConfigRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateApplicationConfigRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'key': json['key'],
        'value': json['value'],
    };
}

export function UpdateApplicationConfigRequestToJSON(value?: UpdateApplicationConfigRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'key': value.key,
        'value': value.value,
    };
}

