/* tslint:disable */
/* eslint-disable */
/**
 * auth
 * Aicacia Auth
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateApplicationRequest
 */
export interface UpdateApplicationRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateApplicationRequest
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateApplicationRequest
     */
    uri?: string | null;
}

/**
 * Check if a given object implements the UpdateApplicationRequest interface.
 */
export function instanceOfUpdateApplicationRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdateApplicationRequestFromJSON(json: any): UpdateApplicationRequest {
    return UpdateApplicationRequestFromJSONTyped(json, false);
}

export function UpdateApplicationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateApplicationRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'uri': !exists(json, 'uri') ? undefined : json['uri'],
    };
}

export function UpdateApplicationRequestToJSON(value?: UpdateApplicationRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'uri': value.uri,
    };
}

