/* tslint:disable */
/* eslint-disable */
/**
 * auth
 * Aicacia Auth API provides authentication services for applications.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserResetPassword
 */
export interface UserResetPassword {
    /**
     * 
     * @type {string}
     * @memberof UserResetPassword
     */
    scope?: string | null;
    /**
     * 
     * @type {number}
     * @memberof UserResetPassword
     */
    tenantId?: number | null;
}

/**
 * Check if a given object implements the UserResetPassword interface.
 */
export function instanceOfUserResetPassword(value: object): value is UserResetPassword {
    return true;
}

export function UserResetPasswordFromJSON(json: any): UserResetPassword {
    return UserResetPasswordFromJSONTyped(json, false);
}

export function UserResetPasswordFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserResetPassword {
    if (json == null) {
        return json;
    }
    return {
        
        'scope': json['scope'] == null ? undefined : json['scope'],
        'tenantId': json['tenant_id'] == null ? undefined : json['tenant_id'],
    };
}

export function UserResetPasswordToJSON(json: any): UserResetPassword {
    return UserResetPasswordToJSONTyped(json, false);
}

export function UserResetPasswordToJSONTyped(value?: UserResetPassword | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'scope': value['scope'],
        'tenant_id': value['tenantId'],
    };
}

