/* tslint:disable */
/* eslint-disable */
/**
 * auth
 * Aicacia Auth API provides authentication services for applications.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserPhoneNumber
 */
export interface UserPhoneNumber {
    /**
     * 
     * @type {Date}
     * @memberof UserPhoneNumber
     */
    createdAt: Date;
    /**
     * 
     * @type {number}
     * @memberof UserPhoneNumber
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof UserPhoneNumber
     */
    phoneNumber: string;
    /**
     * 
     * @type {boolean}
     * @memberof UserPhoneNumber
     */
    primary: boolean;
    /**
     * 
     * @type {Date}
     * @memberof UserPhoneNumber
     */
    updatedAt: Date;
    /**
     * 
     * @type {boolean}
     * @memberof UserPhoneNumber
     */
    verified: boolean;
}

/**
 * Check if a given object implements the UserPhoneNumber interface.
 */
export function instanceOfUserPhoneNumber(value: object): value is UserPhoneNumber {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('phoneNumber' in value) || value['phoneNumber'] === undefined) return false;
    if (!('primary' in value) || value['primary'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('verified' in value) || value['verified'] === undefined) return false;
    return true;
}

export function UserPhoneNumberFromJSON(json: any): UserPhoneNumber {
    return UserPhoneNumberFromJSONTyped(json, false);
}

export function UserPhoneNumberFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserPhoneNumber {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': (new Date(json['created_at'])),
        'id': json['id'],
        'phoneNumber': json['phone_number'],
        'primary': json['primary'],
        'updatedAt': (new Date(json['updated_at'])),
        'verified': json['verified'],
    };
}

export function UserPhoneNumberToJSON(json: any): UserPhoneNumber {
    return UserPhoneNumberToJSONTyped(json, false);
}

export function UserPhoneNumberToJSONTyped(value?: UserPhoneNumber | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': ((value['createdAt']).toISOString()),
        'id': value['id'],
        'phone_number': value['phoneNumber'],
        'primary': value['primary'],
        'updated_at': ((value['updatedAt']).toISOString()),
        'verified': value['verified'],
    };
}

