/* tslint:disable */
/* eslint-disable */
/**
 * auth
 * Aicacia Auth API provides authentication services for applications.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserConfig
 */
export interface UserConfig {
    /**
     * 
     * @type {string}
     * @memberof UserConfig
     */
    mfaType?: string | null;
}

/**
 * Check if a given object implements the UserConfig interface.
 */
export function instanceOfUserConfig(value: object): value is UserConfig {
    return true;
}

export function UserConfigFromJSON(json: any): UserConfig {
    return UserConfigFromJSONTyped(json, false);
}

export function UserConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'mfaType': json['mfa_type'] == null ? undefined : json['mfa_type'],
    };
}

export function UserConfigToJSON(json: any): UserConfig {
    return UserConfigToJSONTyped(json, false);
}

export function UserConfigToJSONTyped(value?: UserConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mfa_type': value['mfaType'],
    };
}

