/* tslint:disable */
/* eslint-disable */
/**
 * auth
 * Aicacia Auth API provides authentication services for applications.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const UserMFAType = {
    None: 'none',
    Totp: 'totp',
    Email: 'email',
    Text: 'text'
} as const;
export type UserMFAType = typeof UserMFAType[keyof typeof UserMFAType];


export function instanceOfUserMFAType(value: any): boolean {
    for (const key in UserMFAType) {
        if (Object.prototype.hasOwnProperty.call(UserMFAType, key)) {
            if (UserMFAType[key as keyof typeof UserMFAType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function UserMFATypeFromJSON(json: any): UserMFAType {
    return UserMFATypeFromJSONTyped(json, false);
}

export function UserMFATypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserMFAType {
    return json as UserMFAType;
}

export function UserMFATypeToJSON(value?: UserMFAType | null): any {
    return value as any;
}

export function UserMFATypeToJSONTyped(value: any, ignoreDiscriminator: boolean): UserMFAType {
    return value as UserMFAType;
}

