/* tslint:disable */
/* eslint-disable */
/**
 * auth
 * Aicacia Auth API provides authentication services for applications.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserInfo
 */
export interface UserInfo {
    /**
     * 
     * @type {string}
     * @memberof UserInfo
     */
    address?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof UserInfo
     */
    birthdate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof UserInfo
     */
    familyName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserInfo
     */
    gender?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserInfo
     */
    givenName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserInfo
     */
    locale?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserInfo
     */
    middleName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserInfo
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserInfo
     */
    nickname?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserInfo
     */
    profilePicture?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserInfo
     */
    website?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserInfo
     */
    zoneInfo?: string | null;
}

/**
 * Check if a given object implements the UserInfo interface.
 */
export function instanceOfUserInfo(value: object): value is UserInfo {
    return true;
}

export function UserInfoFromJSON(json: any): UserInfo {
    return UserInfoFromJSONTyped(json, false);
}

export function UserInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'] == null ? undefined : json['address'],
        'birthdate': json['birthdate'] == null ? undefined : (new Date(json['birthdate'])),
        'familyName': json['family_name'] == null ? undefined : json['family_name'],
        'gender': json['gender'] == null ? undefined : json['gender'],
        'givenName': json['given_name'] == null ? undefined : json['given_name'],
        'locale': json['locale'] == null ? undefined : json['locale'],
        'middleName': json['middle_name'] == null ? undefined : json['middle_name'],
        'name': json['name'] == null ? undefined : json['name'],
        'nickname': json['nickname'] == null ? undefined : json['nickname'],
        'profilePicture': json['profile_picture'] == null ? undefined : json['profile_picture'],
        'website': json['website'] == null ? undefined : json['website'],
        'zoneInfo': json['zone_info'] == null ? undefined : json['zone_info'],
    };
}

export function UserInfoToJSON(json: any): UserInfo {
    return UserInfoToJSONTyped(json, false);
}

export function UserInfoToJSONTyped(value?: UserInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address': value['address'],
        'birthdate': value['birthdate'] == null ? undefined : ((value['birthdate'] as any).toISOString()),
        'family_name': value['familyName'],
        'gender': value['gender'],
        'given_name': value['givenName'],
        'locale': value['locale'],
        'middle_name': value['middleName'],
        'name': value['name'],
        'nickname': value['nickname'],
        'profile_picture': value['profilePicture'],
        'website': value['website'],
        'zone_info': value['zoneInfo'],
    };
}

