/* tslint:disable */
/* eslint-disable */
/**
 * auth
 * Aicacia Auth API provides authentication services for applications.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';

/**
 * 
 * @export
 * @interface UserPagination
 */
export interface UserPagination {
    /**
     * 
     * @type {boolean}
     * @memberof UserPagination
     */
    hasMore: boolean;
    /**
     * 
     * @type {Array<User>}
     * @memberof UserPagination
     */
    items: Array<User>;
}

/**
 * Check if a given object implements the UserPagination interface.
 */
export function instanceOfUserPagination(value: object): value is UserPagination {
    if (!('hasMore' in value) || value['hasMore'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function UserPaginationFromJSON(json: any): UserPagination {
    return UserPaginationFromJSONTyped(json, false);
}

export function UserPaginationFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserPagination {
    if (json == null) {
        return json;
    }
    return {
        
        'hasMore': json['has_more'],
        'items': ((json['items'] as Array<any>).map(UserFromJSON)),
    };
}

export function UserPaginationToJSON(json: any): UserPagination {
    return UserPaginationToJSONTyped(json, false);
}

export function UserPaginationToJSONTyped(value?: UserPagination | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'has_more': value['hasMore'],
        'items': ((value['items'] as Array<any>).map(UserToJSON)),
    };
}

