/* tslint:disable */
/* eslint-disable */
/**
 * auth
 * Aicacia Auth
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Message,
  RequestResetPasswordRequest,
  ResetPasswordRequest,
  SignInWithPasswordRequest,
  SignUpMethods,
  SignUpWithPasswordRequest,
} from '../models/index';
import {
    MessageFromJSON,
    MessageToJSON,
    RequestResetPasswordRequestFromJSON,
    RequestResetPasswordRequestToJSON,
    ResetPasswordRequestFromJSON,
    ResetPasswordRequestToJSON,
    SignInWithPasswordRequestFromJSON,
    SignInWithPasswordRequestToJSON,
    SignUpMethodsFromJSON,
    SignUpMethodsToJSON,
    SignUpWithPasswordRequestFromJSON,
    SignUpWithPasswordRequestToJSON,
} from '../models/index';

export interface ConfirmEmailRequest {
    confirmationToken: string;
}

export interface RequestResetPasswordOperationRequest {
    requestResetPasswordRequest: RequestResetPasswordRequest;
}

export interface ResetPasswordWithTokenRequest {
    resetPasswordRequest: ResetPasswordRequest;
}

export interface SignInWithPasswordOperationRequest {
    signInWithPasswordRequest: SignInWithPasswordRequest;
}

export interface SignUpMethodsRequest {
    applicationId: string;
}

export interface SignUpWithPasswordOperationRequest {
    signUpWithPasswordRequest: SignUpWithPasswordRequest;
}

/**
 * AuthApi - interface
 * 
 * @export
 * @interface AuthApiInterface
 */
export interface AuthApiInterface {
    /**
     * 
     * @param {string} confirmationToken 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApiInterface
     */
    confirmEmailRaw(requestParameters: ConfirmEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    confirmEmail(confirmationToken: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @param {RequestResetPasswordRequest} requestResetPasswordRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApiInterface
     */
    requestResetPasswordRaw(requestParameters: RequestResetPasswordOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    requestResetPassword(requestResetPasswordRequest: RequestResetPasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @param {ResetPasswordRequest} resetPasswordRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApiInterface
     */
    resetPasswordWithTokenRaw(requestParameters: ResetPasswordWithTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>>;

    /**
     */
    resetPasswordWithToken(resetPasswordRequest: ResetPasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string>;

    /**
     * 
     * @param {SignInWithPasswordRequest} signInWithPasswordRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApiInterface
     */
    signInWithPasswordRaw(requestParameters: SignInWithPasswordOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>>;

    /**
     */
    signInWithPassword(signInWithPasswordRequest: SignInWithPasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string>;

    /**
     * 
     * @param {string} applicationId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApiInterface
     */
    signUpMethodsRaw(requestParameters: SignUpMethodsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SignUpMethods>>;

    /**
     */
    signUpMethods(applicationId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SignUpMethods>;

    /**
     * 
     * @param {SignUpWithPasswordRequest} signUpWithPasswordRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApiInterface
     */
    signUpWithPasswordRaw(requestParameters: SignUpWithPasswordOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>>;

    /**
     */
    signUpWithPassword(signUpWithPasswordRequest: SignUpWithPasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string>;

}

/**
 * 
 */
export class AuthApi extends runtime.BaseAPI implements AuthApiInterface {

    /**
     */
    async confirmEmailRaw(requestParameters: ConfirmEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.confirmationToken === null || requestParameters.confirmationToken === undefined) {
            throw new runtime.RequiredError('confirmationToken','Required parameter requestParameters.confirmationToken was null or undefined when calling confirmEmail.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/auth/confirm-email/{confirmation_token}`.replace(`{${"confirmation_token"}}`, encodeURIComponent(String(requestParameters.confirmationToken))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async confirmEmail(confirmationToken: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.confirmEmailRaw({ confirmationToken: confirmationToken }, initOverrides);
    }

    /**
     */
    async requestResetPasswordRaw(requestParameters: RequestResetPasswordOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.requestResetPasswordRequest === null || requestParameters.requestResetPasswordRequest === undefined) {
            throw new runtime.RequiredError('requestResetPasswordRequest','Required parameter requestParameters.requestResetPasswordRequest was null or undefined when calling requestResetPassword.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/auth/request-reset-password`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RequestResetPasswordRequestToJSON(requestParameters.requestResetPasswordRequest),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async requestResetPassword(requestResetPasswordRequest: RequestResetPasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.requestResetPasswordRaw({ requestResetPasswordRequest: requestResetPasswordRequest }, initOverrides);
    }

    /**
     */
    async resetPasswordWithTokenRaw(requestParameters: ResetPasswordWithTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters.resetPasswordRequest === null || requestParameters.resetPasswordRequest === undefined) {
            throw new runtime.RequiredError('resetPasswordRequest','Required parameter requestParameters.resetPasswordRequest was null or undefined when calling resetPasswordWithToken.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/auth/reset-password`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ResetPasswordRequestToJSON(requestParameters.resetPasswordRequest),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async resetPasswordWithToken(resetPasswordRequest: ResetPasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.resetPasswordWithTokenRaw({ resetPasswordRequest: resetPasswordRequest }, initOverrides);
        return await response.value();
    }

    /**
     */
    async signInWithPasswordRaw(requestParameters: SignInWithPasswordOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters.signInWithPasswordRequest === null || requestParameters.signInWithPasswordRequest === undefined) {
            throw new runtime.RequiredError('signInWithPasswordRequest','Required parameter requestParameters.signInWithPasswordRequest was null or undefined when calling signInWithPassword.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/auth/sign-in/password`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SignInWithPasswordRequestToJSON(requestParameters.signInWithPasswordRequest),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async signInWithPassword(signInWithPasswordRequest: SignInWithPasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.signInWithPasswordRaw({ signInWithPasswordRequest: signInWithPasswordRequest }, initOverrides);
        return await response.value();
    }

    /**
     */
    async signUpMethodsRaw(requestParameters: SignUpMethodsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SignUpMethods>> {
        if (requestParameters.applicationId === null || requestParameters.applicationId === undefined) {
            throw new runtime.RequiredError('applicationId','Required parameter requestParameters.applicationId was null or undefined when calling signUpMethods.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Authorization", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/auth/sign-up-methods/{application_id}`.replace(`{${"application_id"}}`, encodeURIComponent(String(requestParameters.applicationId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SignUpMethodsFromJSON(jsonValue));
    }

    /**
     */
    async signUpMethods(applicationId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SignUpMethods> {
        const response = await this.signUpMethodsRaw({ applicationId: applicationId }, initOverrides);
        return await response.value();
    }

    /**
     */
    async signUpWithPasswordRaw(requestParameters: SignUpWithPasswordOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters.signUpWithPasswordRequest === null || requestParameters.signUpWithPasswordRequest === undefined) {
            throw new runtime.RequiredError('signUpWithPasswordRequest','Required parameter requestParameters.signUpWithPasswordRequest was null or undefined when calling signUpWithPassword.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/auth/sign-up/password`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SignUpWithPasswordRequestToJSON(requestParameters.signUpWithPasswordRequest),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async signUpWithPassword(signUpWithPasswordRequest: SignUpWithPasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.signUpWithPasswordRaw({ signUpWithPasswordRequest: signUpWithPasswordRequest }, initOverrides);
        return await response.value();
    }

}
