/* tslint:disable */
/* eslint-disable */
/**
 * auth
 * Aicacia Auth.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: nathanfaucett@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Message,
  OAuth2Application,
} from '../models/index';
import {
    MessageFromJSON,
    MessageToJSON,
    OAuth2ApplicationFromJSON,
    OAuth2ApplicationToJSON,
} from '../models/index';

export interface ApplicationRequest {
    code: string;
}

export interface AuthorizeRequest {
    clientId: number;
    redirectUri: string;
    responseType?: string | null;
    scope?: Array<string> | null;
    state?: string | null;
}

/**
 * Oauth2Api - interface
 * 
 * @export
 * @interface Oauth2ApiInterface
 */
export interface Oauth2ApiInterface {
    /**
     * 
     * @param {string} code 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof Oauth2ApiInterface
     */
    applicationRaw(requestParameters: ApplicationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OAuth2Application>>;

    /**
     */
    application(code: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OAuth2Application>;

    /**
     * 
     * @param {number} clientId 
     * @param {string} redirectUri 
     * @param {string} [responseType] 
     * @param {Array<string>} [scope] 
     * @param {string} [state] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof Oauth2ApiInterface
     */
    authorizeRaw(requestParameters: AuthorizeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    authorize(clientId: number, redirectUri: string, responseType?: string | null, scope?: Array<string> | null, state?: string | null, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class Oauth2Api extends runtime.BaseAPI implements Oauth2ApiInterface {

    /**
     */
    async applicationRaw(requestParameters: ApplicationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OAuth2Application>> {
        if (requestParameters.code === null || requestParameters.code === undefined) {
            throw new runtime.RequiredError('code','Required parameter requestParameters.code was null or undefined when calling application.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/oauth2/{code}/application`.replace(`{${"code"}}`, encodeURIComponent(String(requestParameters.code))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OAuth2ApplicationFromJSON(jsonValue));
    }

    /**
     */
    async application(code: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OAuth2Application> {
        const response = await this.applicationRaw({ code: code }, initOverrides);
        return await response.value();
    }

    /**
     */
    async authorizeRaw(requestParameters: AuthorizeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.clientId === null || requestParameters.clientId === undefined) {
            throw new runtime.RequiredError('clientId','Required parameter requestParameters.clientId was null or undefined when calling authorize.');
        }

        if (requestParameters.redirectUri === null || requestParameters.redirectUri === undefined) {
            throw new runtime.RequiredError('redirectUri','Required parameter requestParameters.redirectUri was null or undefined when calling authorize.');
        }

        const queryParameters: any = {};

        if (requestParameters.clientId !== undefined) {
            queryParameters['client_id'] = requestParameters.clientId;
        }

        if (requestParameters.redirectUri !== undefined) {
            queryParameters['redirect_uri'] = requestParameters.redirectUri;
        }

        if (requestParameters.responseType !== undefined) {
            queryParameters['response_type'] = requestParameters.responseType;
        }

        if (requestParameters.scope) {
            queryParameters['scope'] = requestParameters.scope;
        }

        if (requestParameters.state !== undefined) {
            queryParameters['state'] = requestParameters.state;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/oauth2/authorize`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async authorize(clientId: number, redirectUri: string, responseType?: string | null, scope?: Array<string> | null, state?: string | null, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.authorizeRaw({ clientId: clientId, redirectUri: redirectUri, responseType: responseType, scope: scope, state: state }, initOverrides);
    }

}
