name: Web

on:
  push:
    branches: [main]

jobs:
  pages:
    runs-on: ubuntu-latest
    env:
      PUBLIC_AUTH_URL: https://aicacia.github.io/ts-auth
      USE_BASE_PATH: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 24

      - run: npm install -g pnpm@10
      - run: pnpm install --no-frozen-lockfile
      - run: NODE_ENV=production pnpm run build

      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build